# Generated by Django 2.2.7 on 2019-11-28 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0002_auto_20191110_0327'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courtdistrict',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='courtdistrict',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='court_districts', to='geo.State', verbose_name='State'),
        ),
        migrations.AlterUniqueTogether(
            name='courtdistrict',
            unique_together={('state', 'name')},
        ),
    ]
